version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: chatservice-postgres
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: asdnkl23ddsnjk
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d chatdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  chatservice-1:
    build: .
    container_name: chatservice-app-1
    ports:
      - "8082:8082"
      - "9091:9091"
    environment:
      GRPC_USERSERVICE_ADDRESS: static://host.docker.internal:9090
      GRPC_SERVER_PORT: 9091
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chatdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: asdnkl23ddsnjk
      SPRING_REDIS_HOST: host.docker.internal
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: redewe1234534df
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  chatservice-2:
    build: .
    container_name: chatservice-app-2
    ports:
      - "8083:8083"
      - "9092:9092"
    environment:
      GRPC_USERSERVICE_ADDRESS: static://host.docker.internal:9090
      GRPC_SERVER_PORT: 9092
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chatdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: asdnkl23ddsnjk
      SPRING_REDIS_HOST: host.docker.internal
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: redewe1234534df
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: chatservice-nginx
    ports:
      - "8080:8080"
    depends_on:
      - chatservice-1
      - chatservice-2

volumes:
  postgres-data: